### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by rlems** [schmittjoh/JMSPaymentCoreBundle#159] opened 2014-12-18 09:38 UTC
In the documentation under "Plugins" > "Configuring Your Form Type" (http://jmsyst.com/bundles/JMSPaymentCoreBundle/master/plugins#configuring-your-form-type) it says you should provide the tag "payment.method_type", but this should be "payment.method_form_type".
Otherwise the payment method will not appear in the "jms_choose_payment_method" form.
Hope it can help others

**Comment by regularjack** [comment] 2016-08-17 21:08
Duplicate of #84

**Closed by regularjack** 2016-08-17 21:08 UTC
