### ISSUE TITLE
Could not load type "hidden"

### ISSUE THREAD

**Issue by lefevrejeremy** [schmittjoh/JMSPaymentCoreBundle#214] opened 2017-02-19 19:33 UTC
Hi all,
I have follow the tutorial over the website of jmspaymentcorebundle : http://jmspaymentcorebundle.readthedocs.io/en/stable/payment_form.html

but I block on the create form  I always have this mistake: Could not load type "hidden"

Any Idea about this issue? I'm using the version 3.1.10 of symfony

Thanks for the help

**Comment by regularjack** [comment] 2017-02-26 14:16
Can you create a public repo that reproduces this issue? Not much I can do to help without looking into some code. Thanks.

**Comment by gsouveton** [comment] 2017-06-23 10:38
I encountered the same problem and the JMSPaymentCoreBundle was not faulty. In my case the error came from the Ruudk Stripe bundle which adds Stripe support.
If you like at the file _vendor/ruudk/payment-stripe-bundle/src/Form/CheckoutType.php_ you will see 
`$builder->add('token', 'hidden', array(`
that have to be changed to :
`$builder->add('token', HiddenType::class, array(`

**Comment by regularjack** [comment] 2017-06-29 17:01
Closing since, as mentioned above, this is caused by a plugin.

**Closed by regularjack** 2017-06-29 17:01 UTC
Labels: Support
