### ISSUE TITLE
Allow to override entity fields

### ISSUE THREAD

**Issue by bzis** [schmittjoh/JMSPaymentCoreBundle#146] opened 2014-04-22 17:14 UTC
Hi,
I have a problem with entity amount fields. In the mapping they are decimal(10,5). But 5 digits for the number is not enough for me - I use decimal(9,2) for financial fields.
If the properties in entity fields are protected, not private, it would be possible to override them in own entities. 
Now the only way I see is to redefine all four entities with own complete mapping.
Or maybe there is a better way I don't see?

**Comment by regularjack** [comment] 2016-08-17 21:15
Duplicate of #141

**Closed by regularjack** 2016-08-17 21:15 UTC

**Comment by regularjack** [comment] 2016-10-26 00:19
The documentation now includes a [guide](http://jmspaymentcorebundle.readthedocs.io/en/latest/guides/overriding_entity_mapping.html) on how to override entity mapping.
