### ISSUE TITLE
Custom Plugin Documentation bug

### ISSUE THREAD

**Issue by HectorLinares** [schmittjoh/JMSPaymentCoreBundle#92] opened 2013-01-30 16:37 UTC
Seems to be an error in Custom Plugin documentation. 

Where it says:
services:
    credit_card_type:
        class: CreditCardType
        tags:
            - { name: form.type, alias: credit_card }
            - { name: payment.method_type }

I think its:
services:
    credit_card_type:
        class: CreditCardType
        tags:
            - { name: form.type, alias: credit_card }
            - { name: payment.method_form_type }

Note the "payment.method_form_type" difference

**Comment by regularjack** [comment] 2016-08-17 21:00
Duplicate of #84

**Closed by regularjack** 2016-08-17 21:00 UTC
